### ISSUE TITLE
Submit as a patch to rubygems/rubygems

### ISSUE THREAD

**Issue by qrush** [joshfrench/keycutter#1]
Why hasn't this been done yet? :)

**Comment by joshfrench** [comment]
Half of it made it in: https://github.com/rubygems/rubygems/pull/17

`-k` should work for the `push` and `owners` commands, but managing multiple keys via `gem keys` still requires keycutter. I think I sent the original pull back when rubygems was all POLITICS so who knows how that decision was reached.

**Comment by chadxz** [comment]
Will re-evaluate submitting an issue to rubygems asking for the viability of importing the remainder of the functionality of this tool into core if more interest is shown. Closing this for now.
