### ISSUE TITLE
Bump 1.0.1?

### ISSUE THREAD

**Issue by hsbt** [joshfrench/keycutter#11]
Hi, Could you bump a new release versioned 1.0.1?

v1.0.0 still warns this https://github.com/joshfrench/keycutter/commit/d3c4a1523a96cc65b4dd841063cb549f8e62c449

Thanks!

**Comment by joshfrench** [comment]
All set. Thanks for the nudge!

**Comment by hsbt** [comment]
Confirmed. Thanks!
